# Generated by Django 3.0.5 on 2020-04-26 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('name',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='contactstatus',
            options={'ordering': ('name',), 'verbose_name': 'Статус заявки', 'verbose_name_plural': 'Статусы заявок'},
        ),
        migrations.AlterModelOptions(
            name='desiredcontactmethod',
            options={'ordering': ('name',), 'verbose_name': 'Предпочитаемы метод связи', 'verbose_name_plural': 'Предпочитаемые методы связи'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'Предпрочитаемый метод связи', 'verbose_name_plural': 'Предпрочитаемые методы связи'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='desired_contact_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.DesiredContactMethod', verbose_name='Предпочитаемый метод связи'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=13, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='products',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Products', verbose_name='Предпрочитаемый метод связи'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.ContactStatus', verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='contactstatus',
            name='color_bootstrap',
            field=models.CharField(max_length=40, verbose_name='Цвет в bootstrap'),
        ),
        migrations.AlterField(
            model_name='contactstatus',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='desiredcontactmethod',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Предпочитаемый метод Предпочитаемый метод связи'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название доступных продуктов'),
        ),
    ]
