# Generated by Django 3.0.5 on 2020-04-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200426_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductCategory',
        ),
    ]
