# Generated by Django 3.0.5 on 2020-04-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20200426_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='', max_length=40, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
