# Generated by Django 3.0.5 on 2020-04-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='landing.ProductCategory'),
        ),
    ]
